services:
  node-api:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://localhost:9200}

  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile.react
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - node-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  esdata:
    driver: local
